"""course progress

Revision ID: 0002_course_progress
Revises: 0001
Create Date: 2026-10-08 04:08:41.686455+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002_course_progress'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_slug', sa.String(length=120), nullable=False),
    sa.Column('lecture_path', sa.String(length=1000), nullable=False),
    sa.Column('position_seconds', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_progress')),
    sa.UniqueConstraint('course_slug', 'lecture_path', name=op.f('uq_course_progress_course_slug_lecture_path'))
    )
    op.create_index(op.f('ix_course_progress_course_slug'), 'course_progress', ['course_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_progress_course_slug'), table_name='course_progress')
    op.drop_table('course_progress')
    # ### end Alembic commands ###
