"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-05 21:48:42.094971+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_sessions_token_hash'))
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('password_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_owner')),
    sa.UniqueConstraint('username', name=op.f('uq_owner_username'))
    )
    op.create_table('scheduler_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('library', sa.String(length=32), nullable=False),
    sa.Column('library_version', sa.String(length=32), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('desired_retention', sa.Float(), nullable=False),
    sa.Column('learning_steps_seconds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relearning_steps_seconds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('maximum_interval', sa.Integer(), nullable=False),
    sa.Column('enable_fuzzing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduler_configs')),
    sa.UniqueConstraint('name', name=op.f('uq_scheduler_configs_name'))
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('slug', name=op.f('uq_subjects_slug'))
    )
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_certifications_subject_id_subjects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications')),
    sa.UniqueConstraint('slug', name=op.f('uq_certifications_slug'))
    )
    op.create_table('exam_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certification_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('guide_revision', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('scored_questions', sa.Integer(), nullable=False),
    sa.Column('unscored_questions', sa.Integer(), nullable=False),
    sa.Column('passing_scaled_score', sa.Integer(), nullable=False),
    sa.Column('score_scale_min', sa.Integer(), nullable=False),
    sa.Column('score_scale_max', sa.Integer(), nullable=False),
    sa.Column('format_notes', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('checked_on', sa.Date(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], name=op.f('fk_exam_versions_certification_id_certifications'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_versions')),
    sa.UniqueConstraint('certification_id', 'code', name=op.f('uq_exam_versions_certification_id_code'))
    )
    op.create_table('content_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('exam_version_id', sa.Integer(), nullable=False),
    sa.Column('authored_by', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_version_id'], ['exam_versions.id'], name=op.f('fk_content_packs_exam_version_id_exam_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_packs')),
    sa.UniqueConstraint('slug', name=op.f('uq_content_packs_slug'))
    )
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_version_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('weight_percent', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_version_id'], ['exam_versions.id'], name=op.f('fk_domains_exam_version_id_exam_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domains')),
    sa.UniqueConstraint('exam_version_id', 'code', name=op.f('uq_domains_exam_version_id_code'))
    )
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_version_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('focus', sa.String(length=64), nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_version_id'], ['exam_versions.id'], name=op.f('fk_study_sessions_exam_version_id_exam_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_sessions'))
    )
    op.create_index(op.f('ix_study_sessions_status'), 'study_sessions', ['status'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('preferred_session_minutes', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('active_exam_version_id', sa.Integer(), nullable=True),
    sa.Column('daily_review_limit', sa.Integer(), nullable=False),
    sa.Column('backlog_mode', sa.String(length=16), nullable=False),
    sa.Column('familiar_objective_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_user_settings_singleton')),
    sa.ForeignKeyConstraint(['active_exam_version_id'], ['exam_versions.id'], name=op.f('fk_user_settings_active_exam_version_id_exam_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings'))
    )
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('family_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('user_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['content_packs.id'], name=op.f('fk_content_items_pack_id_content_packs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_items')),
    sa.UniqueConstraint('pack_id', 'item_key', name=op.f('uq_content_items_pack_id_item_key'))
    )
    op.create_index(op.f('ix_content_items_family_key'), 'content_items', ['family_key'], unique=False)
    op.create_index(op.f('ix_content_items_kind'), 'content_items', ['kind'], unique=False)
    op.create_index(op.f('ix_content_items_status'), 'content_items', ['status'], unique=False)
    op.create_table('objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('knowledge', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('fk_objectives_domain_id_domains'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_objectives')),
    sa.UniqueConstraint('domain_id', 'code', name=op.f('uq_objectives_domain_id_code'))
    )
    op.create_table('content_item_objectives',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['content_items.id'], name=op.f('fk_content_item_objectives_item_id_content_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], name=op.f('fk_content_item_objectives_objective_id_objectives'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'objective_id', name=op.f('pk_content_item_objectives'))
    )
    op.create_table('content_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objective_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['content_items.id'], name=op.f('fk_content_revisions_item_id_content_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_revisions')),
    sa.UniqueConstraint('item_id', 'revision', name=op.f('uq_content_revisions_item_id_revision'))
    )
    op.create_index('uq_content_revisions_current', 'content_revisions', ['item_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('item_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('bookmarked', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['content_items.id'], name=op.f('fk_item_progress_item_id_content_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_progress')),
    sa.UniqueConstraint('item_id', name=op.f('uq_item_progress_item_id'))
    )
    op.create_table('lab_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['content_items.id'], name=op.f('fk_lab_evidence_item_id_content_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_evidence'))
    )
    op.create_index(op.f('ix_lab_evidence_item_id'), 'lab_evidence', ['item_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['content_items.id'], name=op.f('fk_notes_item_id_content_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index(op.f('ix_notes_item_id'), 'notes', ['item_id'], unique=False)
    op.create_table('review_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=True),
    sa.Column('source_note_id', sa.Integer(), nullable=True),
    sa.Column('front_md', sa.Text(), nullable=False),
    sa.Column('back_md', sa.Text(), nullable=False),
    sa.Column('user_edited', sa.Boolean(), nullable=False),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduler_config_id', sa.Integer(), nullable=False),
    sa.Column('scheduler_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheduler_config_id'], ['scheduler_configs.id'], name=op.f('fk_review_cards_scheduler_config_id_scheduler_configs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_item_id'], ['content_items.id'], name=op.f('fk_review_cards_source_item_id_content_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], name=op.f('fk_review_cards_source_note_id_notes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_cards'))
    )
    op.create_index(op.f('ix_review_cards_due'), 'review_cards', ['due'], unique=False)
    op.create_index('uq_review_cards_source_item', 'review_cards', ['source_kind', 'source_item_id'], unique=True, postgresql_where=sa.text('source_item_id IS NOT NULL'))
    op.create_index('uq_review_cards_source_note', 'review_cards', ['source_note_id'], unique=True, postgresql_where=sa.text('source_note_id IS NOT NULL'))
    op.create_table('session_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('option_order', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('draft_selection', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('draft_confidence', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['content_items.id'], name=op.f('fk_session_items_item_id_content_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_id'], ['content_revisions.id'], name=op.f('fk_session_items_revision_id_content_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], name=op.f('fk_session_items_session_id_study_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_items')),
    sa.UniqueConstraint('session_id', 'item_id', name=op.f('uq_session_items_session_id_item_id')),
    sa.UniqueConstraint('session_id', 'position', name=op.f('uq_session_items_session_id_position'))
    )
    op.create_index(op.f('ix_session_items_session_id'), 'session_items', ['session_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_item_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('family_key', sa.String(length=100), nullable=False),
    sa.Column('session_kind', sa.String(length=16), nullable=False),
    sa.Column('selected_option_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('first_attempt', sa.Boolean(), nullable=False),
    sa.Column('client_request_id', sa.String(length=64), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['content_items.id'], name=op.f('fk_answers_item_id_content_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_id'], ['content_revisions.id'], name=op.f('fk_answers_revision_id_content_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], name=op.f('fk_answers_session_id_study_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_item_id'], ['session_items.id'], name=op.f('fk_answers_session_item_id_session_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers')),
    sa.UniqueConstraint('client_request_id', name=op.f('uq_answers_client_request_id')),
    sa.UniqueConstraint('session_item_id', name=op.f('uq_answers_session_item_id'))
    )
    op.create_index(op.f('ix_answers_answered_at'), 'answers', ['answered_at'], unique=False)
    op.create_index(op.f('ix_answers_family_key'), 'answers', ['family_key'], unique=False)
    op.create_index(op.f('ix_answers_item_id'), 'answers', ['item_id'], unique=False)
    op.create_index(op.f('ix_answers_session_id'), 'answers', ['session_id'], unique=False)
    op.create_table('review_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_duration_ms', sa.Integer(), nullable=True),
    sa.Column('due_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_before', sa.Integer(), nullable=False),
    sa.Column('state_after', sa.Integer(), nullable=False),
    sa.Column('stability_after', sa.Float(), nullable=True),
    sa.Column('difficulty_after', sa.Float(), nullable=True),
    sa.Column('scheduler_config_id', sa.Integer(), nullable=False),
    sa.Column('scheduler_version', sa.String(length=64), nullable=False),
    sa.Column('client_request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['review_cards.id'], name=op.f('fk_review_events_card_id_review_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduler_config_id'], ['scheduler_configs.id'], name=op.f('fk_review_events_scheduler_config_id_scheduler_configs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_events')),
    sa.UniqueConstraint('client_request_id', name=op.f('uq_review_events_client_request_id'))
    )
    op.create_index(op.f('ix_review_events_card_id'), 'review_events', ['card_id'], unique=False)
    op.create_index(op.f('ix_review_events_reviewed_at'), 'review_events', ['reviewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_events_reviewed_at'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_card_id'), table_name='review_events')
    op.drop_table('review_events')
    op.drop_index(op.f('ix_answers_session_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_item_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_family_key'), table_name='answers')
    op.drop_index(op.f('ix_answers_answered_at'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_session_items_session_id'), table_name='session_items')
    op.drop_table('session_items')
    op.drop_index('uq_review_cards_source_note', table_name='review_cards', postgresql_where=sa.text('source_note_id IS NOT NULL'))
    op.drop_index('uq_review_cards_source_item', table_name='review_cards', postgresql_where=sa.text('source_item_id IS NOT NULL'))
    op.drop_index(op.f('ix_review_cards_due'), table_name='review_cards')
    op.drop_table('review_cards')
    op.drop_index(op.f('ix_notes_item_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_lab_evidence_item_id'), table_name='lab_evidence')
    op.drop_table('lab_evidence')
    op.drop_table('item_progress')
    op.drop_index('uq_content_revisions_current', table_name='content_revisions', postgresql_where=sa.text('is_current'))
    op.drop_table('content_revisions')
    op.drop_table('content_item_objectives')
    op.drop_table('objectives')
    op.drop_index(op.f('ix_content_items_status'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_kind'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_family_key'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_study_sessions_status'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_table('domains')
    op.drop_table('content_packs')
    op.drop_table('exam_versions')
    op.drop_table('certifications')
    op.drop_table('subjects')
    op.drop_table('scheduler_configs')
    op.drop_table('owner')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
